[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.193"
serde_derive = "1.0.193"
serde_json = "1.0.108"
sha2 = "0.10.8"
time = "0.3.31"
